name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      # 3. Install dependencies
      - name: Install Dependencies
        run: yarn install

      # 4. Build the project
      - name: Build Project
        run: yarn build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          # Specify the directory where your build output is located
          path: ./dist
